# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ajubert <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/12/14 16:33:50 by ajubert           #+#    #+#              #
#    Updated: 2016/04/24 10:13:59 by ajubert          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=			libft.a

COMPILER=		gcc

FLAGS=			-Wall -Wextra -Werror -c

INCLUDES=		libft.h get_next_line.h

SRC_C		 =	ft_memset.c\
				ft_bzero.c\
				ft_memcpy.c\
				ft_memccpy.c\
				ft_memmove.c\
				ft_memchr.c\
				ft_memcmp.c\
				ft_strlen.c\
				ft_strcpy.c\
				ft_strncpy.c\
				ft_strcat.c\
				ft_strncat.c\
				ft_strlcat.c\
				ft_strchr.c\
				ft_strrchr.c\
				ft_strstr.c\
				ft_strnstr.c\
				ft_strcmp.c\
				ft_strncmp.c\
				ft_isalpha.c\
				ft_isdigit.c\
				ft_isalnum.c\
				ft_isascii.c\
				ft_isprint.c\
				ft_toupper.c\
				ft_tolower.c\
				ft_atoi.c\
				ft_memalloc.c\
				ft_memdel.c\
				ft_strnew.c\
				ft_strdel.c\
				ft_strclr.c\
				ft_striter.c\
				ft_striteri.c\
				ft_strmap.c\
				ft_strmapi.c\
				ft_strequ.c\
				ft_strnequ.c\
				ft_strdup.c\
				ft_strsub.c\
				ft_strjoin.c\
				ft_strtrim.c\
				ft_putchar.c\
				ft_putchar_fd.c\
				ft_putstr.c\
				ft_putstr_fd.c\
				ft_putendl.c\
				ft_putendl_fd.c\
				ft_strsplit.c\
				ft_putnbr.c\
				ft_putnbr_fd.c\
				ft_itoa.c\
				ft_lstnew.c\
				ft_lstdelone.c\
				ft_lstdel.c\
				ft_lstadd.c\
				ft_lstiter.c\
				ft_lstmap.c\
				ft_lstnew_cpy.c\
				get_next_line.c\
				ft_iterative_power.c\
				ft_swap_char.c\
				ft_itoa_long_long.c\
				ft_unsigned_itoa.c\
				ft_unsigned_long_itoa.c\
				ft_wstrlen.c\
				ft_putstr_size.c\
				ft_strjoin_size.c\
				ft_strnncpy.c\
				ft_strdup_free.c\
				ft_strjoin_free.c\
				ft_atoi_long.c

SRC_O=$(SRC_C:.c=.o)

all: $(NAME)

$(NAME): $(SRC_O)
	ar rc $(NAME) $(SRC_O)
	ranlib $(NAME)

%.o:%.c
	$(COMPILER) $(FLAGS) $(INCLUDES) $<

clean:
	rm -rf $(SRC_O)

fclean: clean
	rm -rf $(NAME)

re: fclean all
